defaults: &defaults
  working_directory: /tmp/build
  parallelism: 4
  docker:
    - image: mumblepins/circleci-dev
      environment:
        DOCKER_IMAGE: "mumblepins/circleci-dev"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and maybe deploy all images
          command: |
            ./splitter.py
            cat dockerlist
            circleci tests split dockerlist | xargs -n 1 ./build.py
      - store_artifacts:
          path: workspace
